import InvitationGuest from '#models/invitation_guest'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await InvitationGuest.createMany([
      {
        guestNames: 'Mr. & Mrs. Eustacio Hadap',
        family: 'Hadap',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Alejandro Segales',
        family: 'Segales',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Franco Castro',
        family: 'Castro',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Alvin Hadap',
        family: 'Hadap',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Ronald Aldrin Hadap',
        family: 'Hadap',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Mischerre Hadap',
        family: 'Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Almira Margaret Segales',
        family: 'Segales',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Shanessa Ghislaine Hadap',
        family: 'Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Akio Hadap',
        family: 'Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Adriel Segales',
        family: 'Segales',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Hans Gabriel Hadap',
        family: 'Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Maxima Ganelo & Family',
        family: 'Ganelo',
        maxGuests: 4,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Cely Mora & Family',
        family: 'Mora',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Fermina Clemente',
        family: 'Clemente',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Ricardo Clemente',
        family: 'Clemente',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Fredy Hadap & Family',
        family: 'Hadap',
        maxGuests: 4,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Evelyn Hadap & Family',
        family: 'Hadap',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Jaspher Juangco and Lucas',
        family: 'Juangco',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Niel Placino',
        family: 'Placino',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Grace Sugatan',
        family: 'Sugatan',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Kelvin Evangelista',
        family: 'Evangelista',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Gizelle and Ms. Renalyn',
        family: 'Gizelle',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Gwenn Laurente',
        family: 'Laurente',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Jennalyn Bonifacio',
        family: 'Bonifacio',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Chaicel Mayonado',
        family: 'Mayonado',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Anna Michelle Vega',
        family: 'Vega',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Rafael Yu',
        family: 'Yu',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Pearl Borja',
        family: 'Borja',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Teoderico Anadon',
        family: 'Anadon',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Dr. Edward & Dr. Florence Isidoro',
        family: 'Isidoro',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Hannah Nicole Isidoro',
        family: 'Isidoro',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Edward Gavin Jr. Isidoro',
        family: 'Isidoro',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Clinton & Mrs. Bridgette Grace Anoche & Isla Flora Garce',
        family: 'Anoche',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Justin Palermo',
        family: 'Palermo',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Rev. Carlo Jeffrey and Mrs. April Love Coronel',
        family: 'Coronel',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Rev. Jerald and Mrs. Lara Joy Sardina',
        family: 'Sardina',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Adelaida Sardina',
        family: 'Sardina',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Laura Sanidad',
        family: 'Sanidad',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. John Wendell Valerio & Ms. Nicole Joyzen Narcelles',
        family: 'Valerio-Narcelles',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Peter Paul Llave and Mr. David Joshua Llave',
        family: 'Llave',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Renen Nathan & Mrs. Alma Cadapan',
        family: 'Cadapan',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Joshua Carillo & Ms. Dorothy Herrera',
        family: 'Carillo',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. and Mrs. Romeo Jr. Requino',
        family: 'Requino',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Lincoln & Mrs. Rustia Anoche',
        family: 'Anoche',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Roslin Anoche',
        family: 'Anoche',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Carl James Anoche',
        family: 'Anoche',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Jupet Carillo',
        family: 'Carillo',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Christine Nicole Carillo',
        family: 'Carillo',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Christian Gumaya',
        family: 'Gumaya',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Aaron John Andres',
        family: 'Andres',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Pedrian Panlilio',
        family: 'Panlilio',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Baby Panlilio',
        family: 'Panlilio',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Carlos Armea',
        family: 'Armea',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Justo Batoon',
        family: 'Batoon',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Diane Jassen Cruz',
        family: 'Cruz',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
    ])
  }
}
