import InvitationGuest from '#models/invitation_guest'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await InvitationGuest.createMany([
      {
        guestNames: 'Mr. & Mrs. Eustacio Hadap',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Alejandro Segales',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Franco Castro',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Alvin Hadap',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Ronald Aldrin Hadap',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Mischerre Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Almira Margaret Segales',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Shanessa Ghislaine Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Akio Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Adriel Segales',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Hans Gabriel Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Maxima Ganelo & Family',
        maxGuests: 4,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Cely Mora & Family',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Fermina Clemente',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Ricardo Clemente',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Fredy Hadap & Family',
        maxGuests: 4,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Evelyn Hadap & Family',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Jaspher Juangco and Lucas',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Niel Placino',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Grace Sugatan',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Kelvin Evangelista',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Gizelle and Ms. Renalyn',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Gwenn Laurente',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Jennalyn Bonifacio',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Chaicel Mayonado',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Anna Michelle Vega',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Rafael Yu',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Pearl Borja',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Teoderico Anadon',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Dr. Edward & Dr. Florence Isidoro',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Hannah Nicole Isidoro',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Edward Gavin Jr. Isidoro',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Clinton & Mrs. Bridgette Grace Anoche & Isla Flora Garce',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Justin Palermo',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Rev. Carlo Jeffrey and Mrs. April Love Coronel',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Rev. Jerald and Mrs. Lara Joy Sardina',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Adelaida Sardina',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Laura Sanidad',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. John Wendell Valerio & Ms. Nicole Joyzen Narcelles',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Peter Paul Llave and Mr. David Joshua Llave',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Renen Nathan & Mrs. Alma Cadapan',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Joshua Carillo & Ms. Dorothy Herrera',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. and Mrs. Romeo Jr. Requino',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Lincoln & Mrs. Rustia Anoche',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Roslin Anoche',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Carl James Anoche',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Jupet Carillo',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Christine Nicole Carillo',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Christian Gumaya',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Aaron John Andres',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Pedrian Panlilio',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Baby Panlilio',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Carlos Armea',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Justo Batoon',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Diane Jassen Cruz',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
    ])
  }
}
