import InvitationGuest from '#models/invitation_guest'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await InvitationGuest.createMany([
      {
        guestNames: 'Mr. & Mrs. Eustacio Hadap',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Alejandro Segales',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 14',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Alvin Hadap',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 16',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Mischerre Hadap',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 97',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 103',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 104',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 98',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 105',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 18',
        maxGuests: 4,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 22',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Fermina Clemente',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 112',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 114 & Family',
        maxGuests: 4,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 21',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 26 and Lucas',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 25',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Grace Sugatan',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 28',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Gizelle and Ms. Renalyn',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Gwenn Laurente',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 29',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 31',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 32',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 34',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 33',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 35',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Dr. Edward & Dr. Florence Isidoro',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 136',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 137',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Clinton & Guest 154 & Isla Flora Garce',
        maxGuests: 3,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 41',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Rev. Carlo Jeffrey and Guest 139',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Rev. Jerald and Mrs. Lara Joy Sardina',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Adelaida Sardina',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mrs. Laura Sanidad',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 40',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 161 and Mr. David Joshua Llave',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Renen Nathan & Guest 164',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. Joshua Carillo & Guest 160',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. and Mrs. Romeo Jr. Requino',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ptr. Lincoln & Guest 150',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 152',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 151',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Jupet Carillo',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 158',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 50',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 42',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Mr. & Mrs. Pedrian Panlilio',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Baby Panlilio',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 51',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Guest 52',
        maxGuests: 2,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        guestNames: 'Ms. Diane Jassen Cruz',
        maxGuests: 1,
        isAttending: null,
        noOfGuestsAttending: 0,
        seatNumber: null,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
    ])
  }
}
