/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Guests: () => import('#controllers/guests_controller'),
  Login: () => import('#controllers/login_controller'),
  Rsvps: () => import('#controllers/rsvps_controller'),
  SeatInquiries: () => import('#controllers/seat_inquiries_controller'),
  Statistics: () => import('#controllers/statistics_controller'),
}
